# Generated by Django 4.2.11 on 2024-03-09 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnayUploadedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OnayRegisterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onay_no', models.CharField(max_length=4)),
                ('onay_aciklama', models.CharField(default='my_default_value', max_length=110)),
                ('onay_tarih', models.DateField(auto_now_add=True)),
                ('onay_odemetutar', models.CharField(default='0,00', max_length=20)),
                ('onay_parabirimi', models.CharField(max_length=20)),
                ('onay_odemeyolu', models.CharField(max_length=20)),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
