# Generated by Django 4.2.11 on 2024-03-23 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('muhapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZiraatUploadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='onayregistermodel',
            name='onay_odemetutar',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='onayregistermodel',
            name='onay_tarih',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='ZiraatRegisterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ziraat_tarih', models.DateField()),
                ('ziraat_firma_adi', models.CharField(max_length=100)),
                ('ziraat_muhasebe_belge_no', models.CharField(max_length=10)),
                ('ziraat_aciklama', models.CharField(max_length=150)),
                ('ziraat_tutar', models.CharField(max_length=20)),
                ('ziraat_para_birimi', models.CharField(max_length=20)),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
